spring.application.name=airbnbApp

server.port=8082
server.servlet.context-path=/api/v1

# 1. Ensure the database 'airbnb' is already created in Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb

# 2. Change 'root' to 'postgres' (unless you manually created a user named root)
spring.datasource.username=postgres
spring.datasource.password=Ritesh@1234
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Explicitly set the Postgres Dialect to avoid "Unable to determine dialect" errors
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

